# Podman Compose for Vivint Security Guard - Rocky Linux Edition
#
# Rocky Linux specific features:
#   - SELinux labels on volumes (:Z for private, :z for shared)
#   - Compatible with RHEL-based systems
#   - Works with podman-compose installed via pip
#
# Usage:
#   1. Copy env.example to .env and fill in your credentials
#   2. Run: podman-compose -f compose-rocky.yaml up -d
#
# For GCE deployment with Tailscale:
#   - Set VIVINT_HUB_IP to your hub's Tailscale IP (or local IP if using subnet routing)
#   - Make sure the VM is connected to your Tailscale network

services:
  security-guard:
    build: .
    container_name: vivint-security-guard
    restart: unless-stopped

    # Environment variables for credentials
    # Option 1: Use .env file (recommended)
    env_file:
      - .env

    # Option 2: Set directly (less secure, visible in process list)
    # environment:
    #   - VIVINT_USERNAME=your@email.com
    #   - VIVINT_PASSWORD=yourpassword
    #   - GEMINI_API_KEY=AIza...
    #   - PUSHOVER_TOKEN=a1b2c3...
    #   - PUSHOVER_USER=u1v2w3...
    #   - VIVINT_HUB_IP=100.x.x.x  # Tailscale IP of your hub

    # Persist data with SELinux labels
    # :Z = Private volume (only this container can access)
    # :z = Shared volume (multiple containers can access)
    # Using bind mount so host credentials are directly accessible
    volumes:
      - ./data:/app/data:Z

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Resource limits for e2-micro (1GB RAM, shared CPU)
    # Note: Using mem_limit/mem_reservation instead of deploy.resources
    # because Podman ignores deploy.resources (Docker Swarm syntax)
    mem_limit: 512M
    mem_reservation: 256M

    # Required for GCP ADC - allows container to access metadata server at 169.254.169.254
    network_mode: host

    # Security options for SELinux
    security_opt:
      - label=type:container_runtime_t

    # Health check - uses the /health/live endpoint
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

